from matplotlib.patches import Patch
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                 Image, Table, TableStyle, HRFlowable)
from reportlab.lib.styles import ParagraphStyle
from datetime import datetime
import os
import utils
import re

class HealthReportPDF:
    """
    Builds a clinical PDF report from metrics and chart filepaths.

    The report is structured in four sections:
        ① Mobility          — steps, walking speed, steadiness, gait metrics
        ② Cardiovascular    — HR, HRV, SpO2, VO2Max (requires Apple Watch)
        ③ Sleep             — sleep duration and quality (requires Apple Watch)
        ④ AI-Generated Summary — narrative conclusions generated by an LLM

    Clinical thresholds passed here are used for alert generation and
    the reference table status column (✓ / ⚠).

    Args:
        metrics             : Dict produced by HealthDataReader.metrics.
        charts              : Dict produced by HealthChartBuilder.build_all().
        patient_name        : Full patient name shown in the report header.
        date_of_birth       : Date of birth string from the XML.
        biological_sex      : Biological sex string from the XML.
        start_date          : First date in the dataset.
        end_date            : Last date in the dataset.
        out_path            : Full path for the output PDF file.
        llm_summary         : Narrative text generated by HealthSummaryGenerator
                               (optional — section is skipped if None).
        llm_model_name      : Label shown in the attribution note under the
                               AI-generated section.
    """

    def __init__(self,
                 metrics: dict,
                 charts: dict,
                 patient_name: str,
                 date_of_birth: str,
                 biological_sex: str,
                 start_date,
                 end_date,
                 out_path: str,
                 llm_summary: str = None,
                 llm_model_name: str = "Gemini (gemini-2.5-flash)"):

        config = utils.read_yml_file("config/params_health.yml")
        self.style_colors = utils.read_yml_file("config/params_styles.yml")['colors']

        self.m                    = metrics
        self.charts               = charts
        self.patient_name         = patient_name
        self.date_of_birth        = date_of_birth
        self.biological_sex       = biological_sex
        self.start_date           = start_date
        self.end_date             = end_date
        self.out_path             = out_path
        self.llm_summary          = llm_summary
        self.llm_model_name       = llm_model_name
        self.threshold_steps_goal = config['threshold_steps_goal']['value']
        self.threshold_steps_low  = config['threshold_steps_low']['value']
        self.threshold_speed_goal = config['threshold_speed_goal']['value']
        self.threshold_steadiness = config['threshold_steadiness']['value']
        self.threshold_hrv        = config['threshold_hrv']['value']
        self.threshold_spo2       = config['threshold_spo2']['value']
        self.threshold_sleep_goal = config['threshold_sleep_goal']['value']
        self.threshold_sleep_min  = config['threshold_sleep_min']['value']
        self.threshold_steps_mid  = config['threshold_steps_mid']['value']

        self._build_styles()

    def _build_styles(self):
        def S(name, **kw): return ParagraphStyle(name, **kw)
        self.ST  = S('T',  fontName='Helvetica-Bold', fontSize=18,
                     textColor=colors.HexColor(self.style_colors["dark"]),   spaceAfter=15)
        self.SS  = S('S',  fontName='Helvetica',      fontSize=9,
                     textColor=colors.HexColor(self.style_colors["muted"]),  spaceAfter=14)
        self.SH  = S('H',  fontName='Helvetica-Bold', fontSize=12,
                     textColor=colors.HexColor(self.style_colors["dark"]),
                     spaceBefore=12, spaceAfter=5)
        self.SH2 = S('H2', fontName='Helvetica-Bold', fontSize=10,
                     textColor=colors.HexColor(self.style_colors["purple"]),
                     spaceBefore=8, spaceAfter=4)
        self.SB  = S('B',  fontName='Helvetica',      fontSize=9,
                     textColor=colors.HexColor('#3A3A3C'),
                     leading=14, spaceAfter=6)
        self.SM  = S('M',  fontName='Helvetica',      fontSize=7.5,
                     textColor=colors.HexColor(self.style_colors["muted"]),  spaceAfter=3)

    # ── helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _na(v, unit=''):
        return '—' if v is None else f'{v} {unit}'.strip()

    def _status_color(self, status: str):
        if any(x in status for x in ['⚠','Low','Below','Frequent','Critical']):
            return colors.HexColor('#FFF3CD'), colors.HexColor('#856404')
        if any(x in status for x in ['✓','Normal','OK','Good','Excellent']):
            return colors.HexColor('#D4EDDA'), colors.HexColor('#155724')
        return colors.white, colors.HexColor(self.style_colors["dark"])

    def _kpi_row(self, values, labels, bg1, bg2):
        t = Table([values, labels], colWidths=[4.1*cm]*4)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0),(-1,0), colors.HexColor(bg1)),
            ('BACKGROUND', (0,1),(-1,1), colors.HexColor(bg2)),
            ('TEXTCOLOR',  (0,0),(-1,-1),colors.white),
            ('FONTNAME',   (0,0),(-1,0), 'Helvetica-Bold'),
            ('FONTNAME',   (0,1),(-1,1), 'Helvetica'),
            ('FONTSIZE',   (0,0),(-1,0), 14),
            ('FONTSIZE',   (0,1),(-1,1), 7.5),
            ('ALIGN',      (0,0),(-1,-1),'CENTER'),
            ('VALIGN',     (0,0),(-1,-1),'MIDDLE'),
            ('TOPPADDING', (0,0),(-1,0), 10),
            ('BOTTOMPADDING',(0,0),(-1,0),10),
            ('TOPPADDING', (0,1),(-1,1), 8),
            ('BOTTOMPADDING',(0,1),(-1,1),10),
            ('GRID',       (0,0),(-1,-1),0.8, colors.white),
        ]))
        return t

    def _ref_table(self, data):
        t = Table(data, colWidths=[4.4*cm, 2.8*cm, 5.0*cm, 4.4*cm])
        style = [
            ('BACKGROUND', (0,0),(-1,0), colors.HexColor(self.style_colors["dark"])),
            ('TEXTCOLOR',  (0,0),(-1,0), colors.white),
            ('FONTNAME',   (0,0),(-1,0), 'Helvetica-Bold'),
            ('FONTNAME',   (0,1),(0,-1), 'Helvetica-Bold'),
            ('FONTSIZE',   (0,0),(-1,-1),8.5),
            ('GRID',       (0,0),(-1,-1),0.3, colors.HexColor(self.style_colors["border"])),
            ('LEFTPADDING',(0,0),(-1,-1),7),
            ('TOPPADDING', (0,0),(-1,-1),5),
            ('BOTTOMPADDING',(0,0),(-1,-1),5),
            ('ROWBACKGROUNDS',(0,1),(-1,-1),
             [colors.white, colors.HexColor(self.style_colors["light"])]),
        ]
        for i, row in enumerate(data[1:], 1):
            bg, fg = self._status_color(row[3])
            style += [('BACKGROUND',(3,i),(3,i),bg),
                      ('TEXTCOLOR', (3,i),(3,i),fg),
                      ('FONTNAME',  (3,i),(3,i),'Helvetica-Bold')]
        t.setStyle(TableStyle(style))
        return t

    def _alert_box(self, alerts):
        if not alerts:
            return None
        def AP(text, bold=False):
            fn = 'Helvetica-Bold' if bold else 'Helvetica'
            return Paragraph(text, ParagraphStyle(
                'a', fontName=fn, fontSize=8.5 if not bold else 10,
                textColor=colors.white, leading=13))
        data = [[AP('Clinical alerts', bold=True)]]
        data += [[AP(a)] for a in alerts]
        t = Table(data, colWidths=[16.6*cm])
        t.setStyle(TableStyle([
            ('BACKGROUND',(0,0),(-1,0),  colors.HexColor('#C0392B')),
            ('BACKGROUND',(0,1),(-1,-1), colors.HexColor('#E74C3C')),
            ('LEFTPADDING',(0,0),(-1,-1),10),
            ('RIGHTPADDING',(0,0),(-1,-1),10),
            ('TOPPADDING',  (0,0),(-1,-1),6),
            ('BOTTOMPADDING',(0,0),(-1,-1),6),
            ('GRID',(0,0),(-1,-1),0.3,colors.HexColor('#C0392B')),
        ]))
        return t

    def _hr_line(self, story, thick=0.8):
        story.append(HRFlowable(width='100%', thickness=thick,
                                 color=colors.HexColor(self.style_colors["border"]),
                                 spaceAfter=10))

    def _img(self, key):
        return Image(self.charts[key], width=16.6*cm, height=4.4*cm)

    def _markdown_bold_to_html(self, text: str) -> str:
        """Convierte **negrita** estilo markdown a <b>negrita</b> para Paragraph."""
        return re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)

    def _add_llm_conclusions(self, story):
        """
        Adds an AI-generated conclusions section, parsing the LLM's
        markdown-style section headers (**HEADER**) into formatted PDF
        headings and body paragraphs, followed by a prominent disclaimer box.
        """
        if not self.llm_summary:
            return

        self._hr_line(story)
        story.append(Paragraph("④ AI-Generated Summary", self.SH))

        for line in self.llm_summary.strip().split('\n'):
            line = line.strip()
            if not line:
                continue

            header_match = re.fullmatch(r'\*\*(.+?)\*\*', line)
            if header_match:
                story.append(Paragraph(header_match.group(1), self.SH2))
            else:
                story.append(Paragraph(self._markdown_bold_to_html(line), self.SB))

        story.append(Spacer(1, 10))
        story.append(self._disclaimer_box(
            "⚠ Please read before use",
            [
                f"This section was generated by {self.llm_model_name}, an AI language model, "
                "based solely on the device metrics shown in this report.",
                "It is a narrative summary of the numbers above, not a medical evaluation, "
                "diagnosis, or clinical recommendation.",
                "AI-generated text may contain errors or misinterpret data. Always verify "
                "against the source metrics and reference tables before relying on it.",
                "This content must be reviewed by a qualified professional before any "
                "clinical or health-related decision is made.",
            ]
        ))
        story.append(Spacer(1, 10))



    def _disclaimer_box(self, title: str, lines: list):
        """
        Builds a prominent boxed disclaimer (bigger and more visible than a
        plain small-print note), used for the AI-generated content warning.
        """
        def DP(text, bold=False, size=9.5):
            fn = 'Helvetica-Bold' if bold else 'Helvetica'
            return Paragraph(text, ParagraphStyle(
                'd', fontName=fn, fontSize=size,
                textColor=colors.HexColor('#5A4A00'), leading=14))

        data = [[DP(title, bold=True, size=11)]]
        data += [[DP(f"•  {line}")] for line in lines]
        t = Table(data, colWidths=[16.6*cm])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0),(-1,0),  colors.HexColor('#FFE69C')),
            ('BACKGROUND', (0,1),(-1,-1), colors.HexColor('#FFF3CD')),
            ('BOX',        (0,0),(-1,-1), 1, colors.HexColor('#E0A800')),
            ('LEFTPADDING',(0,0),(-1,-1),12),
            ('RIGHTPADDING',(0,0),(-1,-1),12),
            ('TOPPADDING',  (0,0),(-1,-1),7),
            ('BOTTOMPADDING',(0,0),(-1,-1),7),
        ]))
        return t

    # ── build ─────────────────────────────────────────────────────────────────

    def build(self):
        """Assemble and save the PDF report."""
        m    = self.m
        na   = self._na
        story= []

        doc = SimpleDocTemplate(
            self.out_path, pagesize=A4,
            leftMargin=2*cm, rightMargin=2*cm,
            topMargin=2*cm,  bottomMargin=2*cm)

        # ── Header
        story.append(Paragraph("Health Summary Report", self.ST))
        story.append(Paragraph(
            f"{self.patient_name}  ·  DOB: {self.date_of_birth}  ·  "
            f"Sex: {self.biological_sex}  ·  "
            f"Period: {self.start_date.strftime('%b %d, %Y')} — "
            f"{self.end_date.strftime('%b %d, %Y')}  ·  "
            f"Generated: {datetime.now().strftime('%b %d, %Y')}",
            self.SS))
        story.append(HRFlowable(width='100%', thickness=1.5,
                                 color=colors.HexColor(self.style_colors["purple"]),
                                 spaceAfter=14))

        # ── Alerts
        alerts = []
        if m['avg_steps'] < self.threshold_steps_goal:
            alerts.append(f"⚠ Avg daily steps ({m['avg_steps']:,}) below {self.threshold_steps_goal:,}/day.")
        if m['days_below_low'] > 5:
            alerts.append(f"⚠ {m['days_below_low']} days under {self.threshold_steps_low:,} steps.")
        if m['avg_speed'] < self.threshold_speed_goal:
            alerts.append(f"⚠ Walking speed ({m['avg_speed']} km/h) below {self.threshold_speed_goal} km/h — fall risk.")
        if m['avg_steadiness'] and m['avg_steadiness'] < self.threshold_steadiness:
            alerts.append(f"⚠ Walking steadiness ({m['avg_steadiness']}) below {self.threshold_steadiness}.")
        if m['avg_hrv'] and m['avg_hrv'] < self.threshold_hrv:
            alerts.append(f"⚠ Low HRV ({m['avg_hrv']} ms) — reduced autonomic recovery.")
        if m['avg_spo2'] and m['avg_spo2'] < self.threshold_spo2:
            alerts.append(f"⚠ SpO2 ({m['avg_spo2']}%) below {self.threshold_spo2}% — monitoring advised.")
        if m['avg_sleep'] and m['avg_sleep'] < self.threshold_sleep_goal:
            alerts.append(f"⚠ Avg sleep ({m['avg_sleep']} h) below recommended {self.threshold_sleep_goal} h.")
        if m['days_poor_sleep'] > 8:
            alerts.append(f"⚠ {m['days_poor_sleep']} nights under {self.threshold_sleep_min} h.")

        ab = self._alert_box(alerts)
        if ab:
            story += [ab, Spacer(1, 14)]

        # ── SECTION 1: MOBILITY ───────────────────────────────────────────────
        story.append(Paragraph("① Mobility", self.SH))
        story.append(self._kpi_row(
            [f'{m["avg_steps"]:,}', na(m['avg_speed'],'km/h'),
             na(m['avg_steadiness']), f'{m["avg_flights"]}'],
            ['Avg daily steps','Walk speed','Steadiness (0–1)','Flights/day'],
            self.style_colors["purple"], self.style_colors["purple2"]))
        story.append(Spacer(1, 6))
        story.append(self._kpi_row(
            [na(m['avg_step_length'],'cm'), na(m['avg_dbl_support'],'%'),
             na(m['avg_asymmetry'],'%'), f'{m["avg_active"]} kcal'],
            ['Step length','Double support','Gait asymmetry','Active cal/day'],
            self.style_colors["pink"], self.style_colors["pink2"]))
        story.append(Spacer(1, 14))

        story.append(Paragraph("Daily step count", self.SH2))
        story.append(Paragraph(
            f"{m['days_below_low']} days under {self.threshold_steps_low:,} steps "
            f"and {m['days_below_mid']} days under {self.threshold_steps_mid:,} in the period.", self.SB))
        story.append(self._img('steps'))
        story.append(Spacer(1, 10))

        story.append(Paragraph("Walking speed and steadiness", self.SH2))
        story.append(Paragraph(
            f"Avg speed {m['avg_speed']} km/h (clinical threshold {self.threshold_speed_goal} km/h). "
            f"{m['days_slow_speed']} days with very low speed.", self.SB))
        story.append(Image(self.charts['mobility'], width=16.6*cm, height=4.2*cm))
        story.append(Spacer(1, 10))

        story.append(Paragraph("Caloric expenditure", self.SH2))
        story.append(Paragraph(
            f"Active avg {m['avg_active']} kcal/day · Basal avg {m['avg_basal']} kcal/day.", self.SB))
        story.append(Image(self.charts['calories'], width=16.6*cm, height=4.2*cm))
        story.append(Spacer(1, 10))

        story.append(self._ref_table([
            ['Metric','Value','Reference','Status'],
            ['Avg daily steps', f'{m["avg_steps"]:,}',
             f'≥ {self.threshold_steps_goal:,}/day',
             '✓ OK' if m['avg_steps'] >= self.threshold_steps_goal else '⚠ Below target'],
            ['Walking speed', na(m['avg_speed'],'km/h'),
             f'≥ {self.threshold_speed_goal} km/h',
             '✓ Normal' if m['avg_speed'] >= self.threshold_speed_goal else '⚠ Low — fall risk'],
            ['Walking steadiness', na(m['avg_steadiness']),
             f'≥ {self.threshold_steadiness}',
             '—' if m['avg_steadiness'] is None
             else ('✓ OK' if m['avg_steadiness'] >= self.threshold_steadiness else '⚠ Low')],
            ['Gait asymmetry', na(m['avg_asymmetry'],'%'),
             '< 8% (symmetric)',
             '—' if m['avg_asymmetry'] is None
             else ('✓ OK' if m['avg_asymmetry'] < 8 else '⚠ Asymmetric')],
            ['Active cal/day', f'{m["avg_active"]} kcal', '200–400 kcal moderate','—'],
        ]))
        story.append(Spacer(1, 16))

        # ── SECTION 2: CARDIOVASCULAR ─────────────────────────────────────────
        self._hr_line(story)
        story.append(Paragraph("② Cardiovascular", self.SH))

        if not m['has_cardio']:
            story.append(Paragraph(
                "No Apple Watch data detected. HR, HRV, SpO2 and VO2Max require an Apple Watch.",
                self.SB))
        else:
            story.append(self._kpi_row(
                [na(m['avg_hr'],'bpm'), na(m['avg_hrv'],'ms'),
                 na(m['avg_spo2'],'%'), na(m['avg_resp'],'/min')],
                ['Resting HR','HRV (SDNN)','SpO2','Resp rate'],
                self.style_colors["purple"], self.style_colors["purple2"]))
            story.append(Spacer(1, 6))
            story.append(self._kpi_row(
                [na(m['avg_vo2'],'mL/min·kg'), na(m['avg_hr_recovery'],'bpm'),
                 na(m['avg_walk_hr'],'bpm'),   na(m['avg_stair_up'],'m/s')],
                ['VO2 Max','HR Recovery 1min','Walking HR avg','Stair ascent'],
                self.style_colors["pink"], self.style_colors["pink2"]))
            story.append(Spacer(1, 14))

            if 'hr_hrv' in self.charts:
                story.append(Paragraph("Resting heart rate and HRV", self.SH2))
                story.append(Paragraph(
                    f"Avg resting HR {m['avg_hr']} bpm · Avg HRV {m['avg_hrv']} ms. "
                    f"HRV below {self.threshold_hrv} ms is associated with reduced autonomic resilience.", self.SB))
                story.append(Image(self.charts['hr_hrv'], width=16.6*cm, height=4.6*cm))
                story.append(Spacer(1, 10))

            if 'spo2' in self.charts:
                story.append(Paragraph("Oxygen saturation (SpO2)", self.SH2))
                story.append(Paragraph(
                    f"Avg SpO2 {m['avg_spo2']}%. Values below {self.threshold_spo2}% require clinical evaluation.", self.SB))
                story.append(Image(self.charts['spo2'], width=16.6*cm, height=4.0*cm))
                story.append(Spacer(1, 10))

            story.append(self._ref_table([
                ['Metric','Value','Reference','Status'],
                ['Resting HR', na(m['avg_hr'],'bpm'), '60–100 bpm',
                 '✓ Normal' if m['avg_hr'] and 60 <= m['avg_hr'] <= 100 else '⚠ Abnormal'],
                ['HRV (SDNN)', na(m['avg_hrv'],'ms'),
                 f'> {self.threshold_hrv} ms recommended',
                 '—' if not m['avg_hrv']
                 else ('✓ Normal' if m['avg_hrv'] >= self.threshold_hrv else '⚠ Low')],
                ['SpO2', na(m['avg_spo2'],'%'),
                 f'≥ {self.threshold_spo2}%',
                 '—' if not m['avg_spo2']
                 else ('✓ Normal' if m['avg_spo2'] >= self.threshold_spo2 else '⚠ Low')],
                ['VO2 Max', na(m['avg_vo2'],'mL/min·kg'),
                 '> 35 mL/min·kg',
                 '—' if not m['avg_vo2']
                 else ('✓ OK' if m['avg_vo2'] >= 35 else '⚠ Low cardio fitness')],
                ['HR Recovery 1min', na(m['avg_hr_recovery'],'bpm'),
                 '> 12 bpm (normal)',
                 '—' if not m['avg_hr_recovery']
                 else ('✓ Good' if m['avg_hr_recovery'] >= 25
                       else '✓ Normal' if m['avg_hr_recovery'] >= 12 else '⚠ Low')],
            ]))
        story.append(Spacer(1, 16))

        # ── SECTION 3: SLEEP ──────────────────────────────────────────────────
        self._hr_line(story)
        story.append(Paragraph("③ Sleep", self.SH))

        if not m['has_sleep'] or m['avg_sleep'] is None:
            story.append(Paragraph(
                f"Sleep staging requires Apple Watch. "
                f"Patient sleep goal: {m.get('sleep_goal', self.threshold_sleep_goal)} h/night.",
                self.SB))
        else:
            story.append(self._kpi_row(
                [f'{m["avg_sleep"]}h', str(m['days_poor_sleep']),
                 str(m['days_ok_sleep']),
                 str(m['days_poor_sleep'] + m['days_ok_sleep'])],
                ['Avg sleep/night',f'Nights < {self.threshold_sleep_min}h',
                 f'Nights ≥ {self.threshold_sleep_goal}h','Days with data'],
                self.style_colors["purple"], self.style_colors["purple2"]))
            story.append(Spacer(1, 14))
            story.append(Paragraph("Sleep duration per night", self.SH2))
            story.append(Paragraph(
                f"Avg {m['avg_sleep']} h/night. "
                f"{m['days_poor_sleep']} nights under {self.threshold_sleep_min} h.", self.SB))
            story.append(self._img('sleep'))
            story.append(Spacer(1, 10))
            story.append(self._ref_table([
                ['Metric','Value','Reference','Status'],
                ['Avg sleep/night', f'{m["avg_sleep"]} h',
                 f'{self.threshold_sleep_goal}–8 h/night',
                 '✓ OK' if m['avg_sleep'] >= self.threshold_sleep_goal else '⚠ Below target'],
                [f'Nights < {self.threshold_sleep_min}h', str(m['days_poor_sleep']),
                 '< 5 nights/90 days',
                 '✓ OK' if m['days_poor_sleep'] <= 5 else '⚠ Frequent'],
                [f'Nights ≥ {self.threshold_sleep_goal}h', str(m['days_ok_sleep']),
                 '> 60 nights/90 days',
                 '✓ Good' if m['days_ok_sleep'] >= 60 else '⚠ Low'],
            ]))
        story.append(Spacer(1, 16))

        # ── SECTION 4: AI-GENERATED CONCLUSIONS ─────────────────────────────
        self._add_llm_conclusions(story)

        # ── Footer ────────────────────────────────────────────────────────────
        watch_note = ("Apple Watch data included." if m['has_cardio']
                      else "No Apple Watch — cardiovascular metrics unavailable.")
        story.append(Paragraph(
            f"Generated from Apple HealthKit export. {watch_note} "
            "Supplementary reference only — does not replace clinical evaluation.", self.SB))
        story.append(Spacer(1, 4))
        self._hr_line(story, thick=0.5)
        story.append(Paragraph(
            f"Apple Health Python Report  ·  {datetime.now().strftime('%Y-%m-%d %H:%M')}  ·  "
            "Synthetic data — educational purposes only  ·  Not for clinical use", self.SM))

        doc.build(story)
        print(f"✓ PDF saved: {self.out_path}")